# Generated by Django 4.1.2 on 2022-12-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0002_iconos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectos',
            name='image2',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
