# Generated by Django 4.1.2 on 2022-12-30 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0005_alter_iconos_image_alter_proyectos_image1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyectos',
            old_name='image1',
            new_name='image',
        ),
    ]
